title: The BCQT Library of <br>Materials Loss for <br>Superconducting Qubits
description: A compilation of resonator loss values from literature
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
